### ISSUE TITLE
pytorch: debug news_encoder call

### ISSUE THREAD

**Issue by simra** [simra/FedNewsRec#3]

**Comment by simra** [comment]
Traceback (most recent call last):
  File "Example_pt.py", line 97, in <module>
    news_scoring = model.news_encoder(torch.from_numpy(news_title)) # ,verbose=0)
  File "/home/rsim/FedNewsRec/code/model_pt.py", line 220, in news_encoder
    news_vec = self.doc_encoder(news_word_vecs)
  File "/home/rsim/anaconda3/envs/fedrec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rsim/FedNewsRec/code/model_pt.py", line 67, in forward
    l_cnnt = self.phase1(x)
  File "/home/rsim/anaconda3/envs/fedrec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rsim/anaconda3/envs/fedrec/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/rsim/anaconda3/envs/fedrec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rsim/anaconda3/envs/fedrec/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/rsim/anaconda3/envs/fedrec/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 299, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.DoubleTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
